package me.lazerka.meme.api;

import com.google.appengine.api.blobstore.BlobKey;
import com.google.appengine.api.datastore.Link;
import com.googlecode.objectify.Ref;
import com.googlecode.objectify.annotation.*;
import org.joda.time.DateTime;

import java.util.ArrayList;
import java.util.List;

/**
 * @author Dzmitry Lazerka
 */
@Entity(name = "Meme")
@Cache
public class Meme {
	@Parent
	Ref<User> creator;

	@Id
	Long id;

	@Index
	DateTime timeCreated;

	@Index
	DateTime timeModified;

	BlobKey blobKey;

	@Ignore
	Link servingUrl;

	final List<Caption> captions = new ArrayList<>(3);

	public Ref<User> getCreatorRef() {
		return creator;
	}

	public void setCreator(Ref<User> creator) {
		this.creator = creator;
	}

	public void setCreator(User creator) {
		this.creator = Ref.create(creator);
	}

	public Long getId() {
		return id;
	}

	/**
	 * Auto-generated by Datastore.
	 */
	private void setId(Long id) {
		this.id = id;
	}

	public DateTime getTimeCreated() {
		return timeCreated;
	}

	public void setTimeCreated(DateTime timeCreated) {
		this.timeCreated = timeCreated;
	}

	public BlobKey getBlobKey() {
		return blobKey;
	}

	public void setBlobKey(BlobKey blobKey) {
		this.blobKey = blobKey;
	}

	public Link getServingUrl() {
		return servingUrl;
	}

	public void setServingUrl(Link servingUrl) {
		this.servingUrl = servingUrl;
	}

	public List<Caption> getCaptions() {
		return captions;
	}

	@Override
	public String toString() {
		return "Meme{" +
				"creator=" + creator +
				", id=" + id +
				", captions=" + captions +
				'}';
	}
}
