package me.lazerka.meme.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.googlecode.objectify.Ref;
import com.googlecode.objectify.annotation.*;
import org.joda.time.DateTime;

import java.util.ArrayList;
import java.util.List;

/**
 * @author Dzmitry Lazerka
 */
@Entity(name = "Meme")
@Cache
public class Meme {
	@Parent
	Ref<User> creator;

	@Id
	Long id;

	@Index
	DateTime createdAt;

	Image image;

	final List<Caption> captions = new ArrayList<>(3);

	public Ref<User> getCreatorRef() {
		return creator;
	}

	@JsonIgnore
	public void setCreator(Ref<User> creator) {
		this.creator = creator;
	}

	@JsonIgnore
	public void setCreator(User creator) {
		this.creator = Ref.create(creator);
	}

	public Long getId() {
		return id;
	}

	/**
	 * Auto-generated by Datastore.
	 */
	private void setId(Long id) {
		this.id = id;
	}

	public DateTime getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(DateTime createdAt) {
		this.createdAt = createdAt;
	}

	public Image getImage() {
		return image;
	}

	public void setImage(Image image) {
		this.image = image;
	}

	public List<Caption> getCaptions() {
		return captions;
	}

	@Override
	public String toString() {
		return "Meme{" +
				"creator=" + creator +
				", id=" + id +
				", createdAt=" + createdAt +
				", image=" + image +
				", captions=" + captions +
				'}';
	}
}
