USE meme;

CREATE TABLE image (
  id LONG PRIMARY KEY AUTO_INCREMENT,
  blobkey VARCHAR(255) NOT NULL,
  filename VARCHAR(255) NOT NULL,
  size INTEGER NOT NULL,
  width INTEGER,
  height INTEGER
);

CREATE TABLE meme (
  id LONG PRIMARY KEY AUTO_INCREMENT,

  created_by VARCHAR(256) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  image_id INTEGER NOT NULL,

  FOREIGN KEY(image_id) REFERENCES image(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE caption (
  id LONG PRIMARY KEY AUTO_INCREMENT,

  meme_id LONG NOT NULL,

  `text` VARCHAR(255), -- See Caption.TEXT_MAX_LENGTH
  top_px INTEGER,

  FOREIGN KEY(meme_id) REFERENCES meme(id)
    ON UPDATE CASCADE ON DELETE CASCADE
);
